// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DayEight$Advent2017 = require("../day8/dayEight.bs.js");
var Solution$Advent2017 = require("../solution.bs.js");

var Part1Test = Solution$Advent2017.Make(DayEight$Advent2017.Part1);

exports.Part1Test = Part1Test;
/* Part1Test Not a pure module */
