// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DayFive$Advent2017  = require("../dayFive.bs.js");
var Solution$Advent2017 = require("../solution.bs.js");

var Part1Test = Solution$Advent2017.Make([
      DayFive$Advent2017.Part1[0],
      DayFive$Advent2017.Part1[2]
    ]);

var Part2Test = Solution$Advent2017.Make([
      DayFive$Advent2017.Part2[0],
      DayFive$Advent2017.Part2[2]
    ]);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
