// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DayFour$Advent2017  = require("../dayFour.bs.js");
var Solution$Advent2017 = require("../solution.bs.js");

var Part1Test = Solution$Advent2017.Make([
      DayFour$Advent2017.Part1[0],
      DayFour$Advent2017.Part1[4]
    ]);

var Part2Test = Solution$Advent2017.Make([
      DayFour$Advent2017.Part2[0],
      DayFour$Advent2017.Part2[5]
    ]);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
