// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils$Advent2017   = require("../Utils.bs.js");
var DayFour$Advent2017 = require("../dayFour.bs.js");

var Part1Test = Utils$Advent2017.Test([
      DayFour$Advent2017.Part1[0],
      DayFour$Advent2017.Part1[4]
    ]);

var Part2Test = Utils$Advent2017.Test([
      DayFour$Advent2017.Part2[0],
      DayFour$Advent2017.Part2[5]
    ]);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
