// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils$Advent2017   = require("../Utils.bs.js");
var DayFive$Advent2017 = require("../dayFive.bs.js");

var Part1Test = Utils$Advent2017.Test([
      DayFive$Advent2017.Part1[0],
      DayFive$Advent2017.Part1[2]
    ]);

var Part2Test = Utils$Advent2017.Test([
      DayFive$Advent2017.Part2[0],
      DayFive$Advent2017.Part2[2]
    ]);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
