// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils$Advent2017  = require("../Utils.bs.js");
var DayOne$Advent2017 = require("../dayOne.bs.js");

var Part1Test = Utils$Advent2017.Test(DayOne$Advent2017.Part1);

var Part2Test = Utils$Advent2017.Test(DayOne$Advent2017.Part2);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
