// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils$Advent2017  = require("../Utils.bs.js");
var DayTwo$Advent2017 = require("../dayTwo.bs.js");

var Part1Test = Utils$Advent2017.Test([
      DayTwo$Advent2017.Part1[0],
      DayTwo$Advent2017.Part1[3]
    ]);

var Part2Test = Utils$Advent2017.Test([
      DayTwo$Advent2017.Part2[0],
      DayTwo$Advent2017.Part2[3]
    ]);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
