// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils$Advent2017    = require("../Utils.bs.js");
var DayThree$Advent2017 = require("../dayThree.bs.js");

var Part1Test = Utils$Advent2017.Test([
      DayThree$Advent2017.Part1[0],
      DayThree$Advent2017.Part1[3]
    ]);

var Part2Test = Utils$Advent2017.Test(DayThree$Advent2017.Part2);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
