// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var DayThree$Advent2017 = require("../dayThree.bs.js");
var Solution$Advent2017 = require("../solution.bs.js");

var Part1Test = Solution$Advent2017.Make([
      DayThree$Advent2017.Part1[0],
      DayThree$Advent2017.Part1[3]
    ]);

var Part2Test = Solution$Advent2017.Make(DayThree$Advent2017.Part2);

exports.Part1Test = Part1Test;
exports.Part2Test = Part2Test;
/* Part1Test Not a pure module */
