// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var Caml_obj   = require("bs-platform/lib/js/caml_obj.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function Test(S) {
  var check = function () {
    return Js_boolean.to_js_boolean(List.for_all((function (v) {
                      return v;
                    }), List.map((function (param) {
                          return Caml_obj.caml_equal(Curry._1(S[/* solve */1], param[0]), param[1]);
                        }), S[/* cases */0])));
  };
  return /* module */[/* check */check];
}

exports.Test = Test;
/* No side effect */
